In [26]:
import torch

# Introduction To Tensor

In [27]:
#Scalar Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#Dimension
scalar.ndim

0

In [5]:
#Getting the value of tensor
scalar.item()

7

In [6]:
#Vector Tensor
vector = torch.tensor([7,7,7])

In [7]:
#Dimenstion of vector -- No of pair of square Brackets ecnclosed inside the outer square brackets
vector.ndim

1

In [8]:
#Shape of vector --[(Shape),(No of elements in a side on pair of square bracket)] if shape 1 then shape not written
vector.shape

torch.Size([3])

In [9]:
#MATRIX
MATRIX = torch.tensor([[2,3],
                     [4,5]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Elements in particular row of matrix to be shown like below
MATRIX[1]

tensor([4, 5])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]],
                       [[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
#basic structure tensor:[[[here is ur one 'matrix/vector/scalar']]]
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]],

        [[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape
#It means that that their is two set of 3x3 matrix
#1st element lines up with the number of set of outer most bracket.
#The 2nd element lines up with number of square brackets inside the 2nd pair of brackets
#The 3rd element lines up with the number of elements in the the innner most bracket

torch.Size([2, 3, 3])

### Random tensors
Random Tensors formed -> Analyze Data -> Reshape tensors -> Analyze Data -> Reshape Tensors ->....

In [16]:
random_tensor = torch.rand(size=(2,3))
random_tensor.dtype
random_tensor

tensor([[0.0411, 0.6578, 0.7717],
        [0.0998, 0.2500, 0.3497]])

In [17]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='cuda', # defaults to None, which uses the default tensor type cuda for gpu
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

### Matrix Multiplication in Tensors

In [18]:
#use torch.matmul() for matrix multiplication torch.mm() shortcut
#shape valid of format :(m,n)*(n,m)

tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]], dtype = torch.float32)
tensor_b = torch.tensor([[1,2],
                        [3,4],
                        [5,6]], dtype = torch.float32)

#torch_a*torch_b --> shape error -> (3,2)*(3,2)
#Correct method
#tensor_a*tensor_b --> is element by element multiplcation and .matmul() is matrix multiplication
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

In [19]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_a
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [20]:
print(tensor_a.min()) # minimum from tensors
print(tensor_a.max()) # max value from the tensors
print(tensor_a.mean()) # mean of all values of tensors
# if arg used before min and max the index is returned instead of value

tensor(1.)
tensor(6.)
tensor(3.5000)


In [21]:
torch.arange(10,100,10) # creates a a tensor from 10 to 100 with increment of 10 in each value

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
tensor_a.shape

torch.Size([3, 2])

In [28]:
x = torch.rand(size = (2,1,3))
x

tensor([[[0.1053, 0.2695, 0.3588]],

        [[0.1994, 0.5472, 0.0062]]])

In [24]:
#reshape use .reshape(a,b) or .view(a,b). View can be used directly and for reshape u would have to create a new variable
#In view the orignal tensor shape values are not changed

x.view(3,2)
x_reshape = x.reshape(3,2)
x,x_reshape

(tensor([[[0.2666, 0.6274, 0.2696]],
 
         [[0.4414, 0.2969, 0.8317]]]),
 tensor([[0.2666, 0.6274],
         [0.2696, 0.4414],
         [0.2969, 0.8317]]))

In [31]:
# To join 2 tensors use torch.stack(<tupple of tensors>)
x_stacked = torch.stack([x,x])
x_stacked

tensor([[[[0.1053, 0.2695, 0.3588]],

         [[0.1994, 0.5472, 0.0062]]],


        [[[0.1053, 0.2695, 0.3588]],

         [[0.1994, 0.5472, 0.0062]]]])

In [35]:
a = torch.rand(size = (7,1))
a

tensor([[0.7890],
        [0.2814],
        [0.7886],
        [0.5895],
        [0.7539],
        [0.1952],
        [0.0050]])

In [36]:
#to remove unwanted dimensions or in general delete dimension 1 from the dimension of tensors use torch.squeeze()
a_squeezed = torch.squeeze(a)
a_squeezed#the dimension of 1 removed and elements in the tensors are rearranged

tensor([0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050])

In [43]:
#Reverse of squeeze() is torch.unsqueeze() i.e. to add dimension of 1 any where in the tensor or at a praticular dimension vale
a_unsqueezed1 = torch.unsqueeze(a,dim=0)
a_unsqueezed2 = torch.unsqueeze(a,dim=2)# here at dim=1 automatic 1 is added and then 2 
a_unsqueezed1,a_unsqueezed2,a_unsqueezed2.shape

(tensor([[[0.7890],
          [0.2814],
          [0.7886],
          [0.5895],
          [0.7539],
          [0.1952],
          [0.0050]]]),
 tensor([[[0.7890]],
 
         [[0.2814]],
 
         [[0.7886]],
 
         [[0.5895]],
 
         [[0.7539]],
 
         [[0.1952]],
 
         [[0.0050]]]),
 torch.Size([7, 1, 1]))

In [47]:
y = torch.rand(size = (224,225,5))

In [48]:
# to rearrange the dimension use permute 
y_permute = y.permute((2,1,0)) # now 224 is the last dim in shape, 225 is the 2nd dim and 5 is the 1st dim in the shape pf y. The elemenst are hence rearranged in the new shape after using permute
y_permute.shape

torch.Size([5, 225, 224])